erDiagram
    Payment {
        Long Id
        String orderId
        String paymentId
        String refundId
        String status
        Double amount
        String currency
        String invoiceNumber        
    }
