erDiagram
    USER {
        Long id PK
        String name
        String email
        String address
    }
    
    CART {
        Long id PK
        Long user_id FK
        double totalPrice
    }
    
    CART_ITEM {
        Long id PK
        Long cart_id FK
        Long product_id FK
        int quantity
    }
    
    PRODUCT {
        Long id PK
        String title
        String description
        double price
        int stockQuantity
        double rating
        Long category_id FK
    }
    
    CATEGORY {
        Long id PK
        String name
    }
    
    ORDER {
        Long id PK
        Long user_id FK
        double totalAmount
        String paymentMethod
        String paymentStatus
        String orderStatus
        String trackingNumber
        String transactionId
    }
    
    ORDER_ITEM {
        Long id PK
        Long order_id FK
        Long product_id FK
        int quantity
        double priceAtPurchase
    }
    
    USER ||--|{ CART : owns
    CART ||--|{ CART_ITEM : contains
    CART_ITEM }|--|| PRODUCT : contains
    
    ORDER ||--|{ ORDER_ITEM : has
    ORDER }|--|| USER : placed_by
    ORDER_ITEM }|--|| PRODUCT : contains
    
    PRODUCT }|--|| CATEGORY : belongs_to
