graph TD;
    A[Client] --> |Routes Requests| B[User Service];    
    A --> |Routes Requests| C[Product Service];    
    C --> |Routes Requests| D[Payment Service];    
    B -->|Uses| G[MySQL];
    C -->|Uses| G;
    D -->|Uses| G;
    E[Notification Service] -->|Sends Events| J[Kafka Message Broker];
        
    subgraph Client
        A
    end

    subgraph Caching
        M[Redis]
    end
    M --> C;

    subgraph Databases        
        G;
    end

    subgraph Message Broker
        J;
    end

    C -->|Publishes| J;
    J -->|Subscribes| E;
